require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ClientesController do

  def mock_cliente(stubs={})
    @mock_cliente ||= mock_model(Cliente, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all clientes as @clientes" do
      Cliente.stub(:all) { [mock_cliente] }
      get :index
      assigns(:clientes).should eq([mock_cliente])
    end
  end

  describe "GET show" do
    it "assigns the requested cliente as @cliente" do
      Cliente.stub(:find).with("37") { mock_cliente }
      get :show, :id => "37"
      assigns(:cliente).should be(mock_cliente)
    end
  end

  describe "GET new" do
    it "assigns a new cliente as @cliente" do
      Cliente.stub(:new) { mock_cliente }
      get :new
      assigns(:cliente).should be(mock_cliente)
    end
  end

  describe "GET edit" do
    it "assigns the requested cliente as @cliente" do
      Cliente.stub(:find).with("37") { mock_cliente }
      get :edit, :id => "37"
      assigns(:cliente).should be(mock_cliente)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cliente as @cliente" do
        Cliente.stub(:new).with({'these' => 'params'}) { mock_cliente(:save => true) }
        post :create, :cliente => {'these' => 'params'}
        assigns(:cliente).should be(mock_cliente)
      end

      it "redirects to the created cliente" do
        Cliente.stub(:new) { mock_cliente(:save => true) }
        post :create, :cliente => {}
        response.should redirect_to(cliente_url(mock_cliente))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cliente as @cliente" do
        Cliente.stub(:new).with({'these' => 'params'}) { mock_cliente(:save => false) }
        post :create, :cliente => {'these' => 'params'}
        assigns(:cliente).should be(mock_cliente)
      end

      it "re-renders the 'new' template" do
        Cliente.stub(:new) { mock_cliente(:save => false) }
        post :create, :cliente => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cliente" do
        Cliente.stub(:find).with("37") { mock_cliente }
        mock_cliente.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cliente => {'these' => 'params'}
      end

      it "assigns the requested cliente as @cliente" do
        Cliente.stub(:find) { mock_cliente(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cliente).should be(mock_cliente)
      end

      it "redirects to the cliente" do
        Cliente.stub(:find) { mock_cliente(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cliente_url(mock_cliente))
      end
    end

    describe "with invalid params" do
      it "assigns the cliente as @cliente" do
        Cliente.stub(:find) { mock_cliente(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cliente).should be(mock_cliente)
      end

      it "re-renders the 'edit' template" do
        Cliente.stub(:find) { mock_cliente(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cliente" do
      Cliente.stub(:find).with("37") { mock_cliente }
      mock_cliente.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the clientes list" do
      Cliente.stub(:find) { mock_cliente }
      delete :destroy, :id => "1"
      response.should redirect_to(clientes_url)
    end
  end

end
