require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QualificacoesController do

  def mock_qualificacao(stubs={})
    @mock_qualificacao ||= mock_model(Qualificacao, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all qualificacoes as @qualificacoes" do
      Qualificacao.stub(:all) { [mock_qualificacao] }
      get :index
      assigns(:qualificacoes).should eq([mock_qualificacao])
    end
  end

  describe "GET show" do
    it "assigns the requested qualificacao as @qualificacao" do
      Qualificacao.stub(:find).with("37") { mock_qualificacao }
      get :show, :id => "37"
      assigns(:qualificacao).should be(mock_qualificacao)
    end
  end

  describe "GET new" do
    it "assigns a new qualificacao as @qualificacao" do
      Qualificacao.stub(:new) { mock_qualificacao }
      get :new
      assigns(:qualificacao).should be(mock_qualificacao)
    end
  end

  describe "GET edit" do
    it "assigns the requested qualificacao as @qualificacao" do
      Qualificacao.stub(:find).with("37") { mock_qualificacao }
      get :edit, :id => "37"
      assigns(:qualificacao).should be(mock_qualificacao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created qualificacao as @qualificacao" do
        Qualificacao.stub(:new).with({'these' => 'params'}) { mock_qualificacao(:save => true) }
        post :create, :qualificacao => {'these' => 'params'}
        assigns(:qualificacao).should be(mock_qualificacao)
      end

      it "redirects to the created qualificacao" do
        Qualificacao.stub(:new) { mock_qualificacao(:save => true) }
        post :create, :qualificacao => {}
        response.should redirect_to(qualificacao_url(mock_qualificacao))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved qualificacao as @qualificacao" do
        Qualificacao.stub(:new).with({'these' => 'params'}) { mock_qualificacao(:save => false) }
        post :create, :qualificacao => {'these' => 'params'}
        assigns(:qualificacao).should be(mock_qualificacao)
      end

      it "re-renders the 'new' template" do
        Qualificacao.stub(:new) { mock_qualificacao(:save => false) }
        post :create, :qualificacao => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested qualificacao" do
        Qualificacao.stub(:find).with("37") { mock_qualificacao }
        mock_qualificacao.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :qualificacao => {'these' => 'params'}
      end

      it "assigns the requested qualificacao as @qualificacao" do
        Qualificacao.stub(:find) { mock_qualificacao(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:qualificacao).should be(mock_qualificacao)
      end

      it "redirects to the qualificacao" do
        Qualificacao.stub(:find) { mock_qualificacao(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(qualificacao_url(mock_qualificacao))
      end
    end

    describe "with invalid params" do
      it "assigns the qualificacao as @qualificacao" do
        Qualificacao.stub(:find) { mock_qualificacao(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:qualificacao).should be(mock_qualificacao)
      end

      it "re-renders the 'edit' template" do
        Qualificacao.stub(:find) { mock_qualificacao(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested qualificacao" do
      Qualificacao.stub(:find).with("37") { mock_qualificacao }
      mock_qualificacao.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the qualificacoes list" do
      Qualificacao.stub(:find) { mock_qualificacao }
      delete :destroy, :id => "1"
      response.should redirect_to(qualificacoes_url)
    end
  end

end
